FROM oraclelinux:9
ENV PYTHONUNBUFFERED=1

RUN dnf install epel-release -y
RUN dnf install python3 -y
RUN dnf install python3-pip -y
RUN dnf install ncurses -y
RUN dnf install iputils -y
RUN dnf install traceroute -y
RUN dnf install iproute -y
RUN dnf install -y python3-flask
RUN dnf install -y python3-gevent
RUN dnf install -y python3-flask
RUN dnf install -y python3-redis
RUN dnf install -y python3-gunicorn
RUN dnf install -y python3-lxml
RUN dnf install -y python3-defusedxml
RUN dnf install -y python3-pyodbc
RUN dnf install -y git
RUN curl -o /etc/yum.repos.d/msprod.repo https://packages.microsoft.com/config/rhel/9/prod.repo
RUN ACCEPT_EULA=Y dnf install -y msodbcsql17 unixODBC

RUN pip3 install cryptography #for EVBS encryption
ADD requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt # No longer required.

ADD ./server:/opt/VulcanActivityTracker/platform/server/
ADD ./shared /opt/VulcanActivityTracker/platform/shared/
ADD ./web /opt/VulcanActivityTracker/platform/web/
ADD ./templates /opt/VulcanActivityTracker/platform/templates/
RUN mkdir -p /var/VulcanActivityTracker/platform/



WORKDIR /opt/VulcanActivityTracker/platform/web

EXPOSE 6455
ENV VulcanDEV=1

CMD ["python3", "dev-entrypoint.py"]